- include: checkfirewall.yaml

- name: Add service firewall rule (public access)
  lineinfile: dest=/etc/firewall state=present regexp="^iptables -A INPUT -p tcp --dport 9999" line="iptables -A INPUT -p tcp --dport 9999 -j ACCEPT"

- name: Execute firewall
  command: /etc/firewall

- name: Install host packages for debootstrp
  apt: pkg=build-essential,debootstrap,subversion,tmux,lib32stdc++6
- name: Install nsjail
  copy: src=../../distfiles/nsjail/nsjail dest=/srv/nsjail owner=root group=root mode=0700

- name: Install task init file
  copy: src=../../files/spoonknifeand/init.conf dest=/etc/init/spoonknifeand.conf mode=0755
- name: Debootstrap Ubuntu Trusty
  command: debootstrap --include=python,python-crypto trusty /srv/chroot-trusty creates=/srv/chroot-trusty
  notify:
    - restart spoonknifeand
- name: Enable security updates in chroot
  lineinfile: dest=/srv/chroot-trusty/etc/apt/sources.list line="deb http://mirror.rackspace.com/ubuntu trusty-security main restricted"
- name: Upgrade chroot
  command: chroot /srv/chroot-trusty bash -c "apt-get -y update && apt-get -y upgrade"
  notify:
    - restart spoonknifeand
- name: Create task user
  command: chroot /srv/chroot-trusty useradd -m spoonknifeand creates=/srv/chroot-trusty/home/spoonknifeand
- name: Install task files
  synchronize: src=../../distfiles/spoon-knife-and/ dest=/srv/chroot-trusty/home/spoonknifeand delete=yes
  notify:
    - restart spoonknifeand
- name: Install 32bit lib32stdc
  command: chroot /srv/chroot-trusty apt-get -y install lib32stdc++6
- name: Chown whole chroot to root
  command: chown -R root:root /srv/chroot-trusty
- name: Give minimum permissions to task user
  command: chmod -R 755 /srv/chroot-trusty/home/spoonknifeand
