  - name: First-time set up base production wan instances
    hosts: ctf-prod-wan
    remote_user: ubuntu
    become: yes
    tasks:
      - include: tasks/infrastructure-first.yaml env_name=production env_short=prod dc=local
    handlers:
      - name: reload ssh
        service: name=ssh state=reloadedg

  - name: Remove sudo from new hosts
    hosts: ctf-prod-wan
    remote_user: root
    tasks:
      - name: Remove ubuntu user
        user: name=ubuntu state=absent remove=yes
      - name: Remove sudo (1)
        shell: DEBIAN_FRONTEND=noninteractive SUDO_FORCE_REMOVE=yes apt-get -y purge ubuntu-minimal
      - name: Remove sudo (2)
        shell: DEBIAN_FRONTEND=noninteractive SUDO_FORCE_REMOVE=yes apt-get -y purge sudo